#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     - Driving Striaght Challenge -                                 *|
|*                                        Gloria Ngan and CJ Zhang                                    *|
|*                                                                                                    *|
|*                                         ROBOT CONFIGURATION                                        *|
|*                                                                                                    *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:          3+                                                                   *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 10   rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 1    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void forward (int x, int y)
{
	// Clear Encoders
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

  //250 ticks
	//the acceleration (reduces probability of robot moving off from a straight line
	for(int i = 0; i <= y; i = i + 10)
  {
		motor[rightMotor] = i;		  // Motor on port10 is run forward
		motor[leftMotor]  = i;		  // Motor on port1 is run forward
		wait1Msec(200);	        		// Robot runs previous code for 100 milliseconds before moving on
	}

	//auto-correction code that programs the robot to move in straight line
	while (SensorValue[rightEncoder] < x)
		{
			if(SensorValue[rightEncoder] > - SensorValue[leftEncoder])
			{
				motor[rightMotor] = y - 5;
				motor[leftMotor] = y;
			}

			if(SensorValue[rightEncoder] < - SensorValue[leftEncoder])
			{
				motor[rightMotor] = y;
				motor[leftMotor] = y - 5;
			}

			if(SensorValue[rightEncoder] == - SensorValue[leftEncoder])
			{
				motor[rightMotor] = y - 5;
				motor[leftMotor] = y;
			}
		}

	//260 ticks
	for(int i = y; i >= 0; i = i - 10)
	{
		motor[rightMotor] = i;		  // Motor on port10 is run forward
		motor[leftMotor]  = i;		  // Motor on port1 is run forward
		wait1Msec(200);	       			// Robot runs previous code for 200 milliseconds before moving on
	}
}


task main()
{
	forward(2400, 60);
}
