#pragma config(Motor,  port1,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                               	  - Dual Joystick Control w Arm -                                   *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                      Gloria Ngan and CJ Zhang                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 10         rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 1          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

	void drive(int x){
		motor[leftMotor]  = 61 * x;
    motor[rightMotor] = 60 * x;
	}

	void armMove(int x){
		motor[armMotor] = 20 * x;		// if x is positive, the arm moves up
	}

task main ()
{
	while(1 == 1)
	{
				drive(0);

		// While upper left trigger is held, the joystick values are halved for a slower speed.
    	if(vexRT[Btn5U] == 1){

    		motor[leftMotor]  = -vexRT[Ch3]/2;   // Left Joystick Y value
      	motor[rightMotor] = -vexRT[Ch2]/2;   // Right Joystick Y value

      	// If upper right trigger is held, arm moves up.
      	if(vexRT[Btn6U] == 1){
      		armMove(1);
      	}
      	else if(vexRT[Btn6D] == 1){
      		armMove(-1);
      	}
      	else{
      		armMove(0);
      	}
   		}

			// If trigger isn't held, the joystick values are directly mapped to the motors.
			else {
      	motor[leftMotor]  = -vexRT[Ch3];   // Left Joystick Y value
      	motor[rightMotor] = -vexRT[Ch2];   // Right Joystick Y value

      	// If upper right trigger is held, arm moves up.
      	if(vexRT[Btn6U] == 1){
      		armMove(1);
      	}
      	else if(vexRT[Btn6D] == 1){
      		armMove(-1);
      	}
      	else{
      		armMove(0);
      	}
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
