#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward for 5 rotations of the left shaft encoder.       *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*
|*                                                                                                    *|
|*    MOTORS & SENSORS:          3+
                                                                     *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

////point turn 360
//void turnP(int x)
//{
//	while (SensorValue[rightEncoder]< 1820)
//	{
//		motor[rightMotor] = 45;
//		motor[leftMotor] = -45;
//	}
//}

////point turn 180
//void turnP(int x)
//{
//	while (SensorValue[rightEncoder]< 825)
//	{
//		motor[rightMotor] = 96;
//		motor[leftMotor] = -96;
//	}
//}

////point turn 90
//void turnP(int x)
//{
//	while (SensorValue[rightEncoder]< 404)
//	{
//		motor[rightMotor] = 96;
//		motor[leftMotor] = -96;
//	}
//}

////point turn 60
//void turnP(int x)
//{
//	while (SensorValue[rightEncoder]< 275)
//	{
//		motor[rightMotor] = 96;
//		motor[leftMotor] = -96;
//	}
//}

////point turn 45
//void turnP(int x)
//{
//	while (SensorValue[rightEncoder]< 202)
//	{
//		motor[rightMotor] = 96;
//		motor[leftMotor] = -96;
//	}
//}

//point turn 15
void turnP(int x)
{
	while (SensorValue[rightEncoder]< 65)
	{
		motor[rightMotor] = 96;
		motor[leftMotor] = -96;
	}
}

task main()
{
	  wait1Msec(2000);  // 2 Second Delay

	  // Clear Encoders
	  SensorValue[rightEncoder] = 0;
	  SensorValue[leftEncoder] = 0;

	  turnP(1);

}
