#pragma config(Motor,  port1,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                   	  - Quad Button Control -                                       *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                      Gloria Ngan and CJ Zhang                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 10         rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 1          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

void drive(int x){
		motor[leftMotor]  = 61 * x;
    motor[rightMotor] = 60 * x;
	}

	void turn(int x, int y){
		motor[leftMotor]  = 60 * x;
    motor[rightMotor] = 60 * y;
	}

	void armMove(int x){
		motor[armMotor] = 20 * x;		// if x is positive, the arm moves up
	}

task main ()
{
	//Constantly refreshes motor values with values from joystick.
  while(1 == 1)
  {
  	drive(0);
  	armMove(0);

  	// drives forwards
    while(vexRT[Btn8U] == 1){
    	drive(1);
		}
		// drives backwards
   	while(vexRT[Btn8D] == 1){
   		drive(-1);
 	 	}
 	 	// turns left
   	while(vexRT[Btn8L] == 1){
   		turn(-1,1);
 	 	}
		// turns right
 	  while(vexRT[Btn8R] == 1){
 	  	turn(1, -1);
 	 	}

 	 	if(vexRT[Btn6U] == 1){
 	 		armMove(1);
 		}
 		else if(vexRT[Btn6D] == 1){
 			armMove(-1);
 		}
 	 	else{
 	 		armMove(0);
 		}
  }

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
