#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port10,           rightMotor,    tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port1,          leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard

//Clear the encoders associated with the left and right motors.
void resetEncoder(){
	SensorValue[rightIEM] = 0;
	SensorValue[leftIEM] = 0;
}

//Function to turn 90 degrees left or right, depending on whether x is pos/neg.
void turn90(int x){
	resetEncoder();
	wait1Msec(1000);

	while (SensorValue[leftIEM]< 160){
		motor[leftMotor] = 2 * x;
		motor[rightMotor] = 2 * -x;
	}
}

task main()
{

turn90(1);

}
