#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward for 5 rotations of the left shaft encoder.       *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*
|*                                                                                                    *|
|*    MOTORS & SENSORS:          3+
                                                                     *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++


////swing turn turn 180
//void turnS(int x)
//{
//	while (SensorValue[rightEncoder]< 1720)
//	{
//		motor[rightMotor] = 45;
//	}
//}

////swing turn turn 90
//void turnS(int x)
//{
//	while (SensorValue[rightEncoder]< 860)
//	{
//		motor[rightMotor] = 96;
//	}
//}

////swing turn turn 60
//void turnS(int x)
//{
//	while (SensorValue[rightEncoder]< 573)
//	{
//		motor[rightMotor] = 96;
//	}
//}

////swing turn turn 45
//void turnS(int x)
//{
//	while (SensorValue[rightEncoder]< 430)
//	{
//		motor[rightMotor] = 96;
//	}
//}

//swing turn turn 15
void turnS(int x)
{
	while (SensorValue[rightEncoder]< 143)
	{
		motor[rightMotor] = 45;
	}
}

task main()
{
	  wait1Msec(2000);  // 2 Second Delay

	  // Clear Encoders
	  SensorValue[rightEncoder] = 0;
	  SensorValue[leftEncoder] = 0;

	  turnS(1);

}
